### ISSUE TITLE
support non unicode pages.

### ISSUE THREAD

**Issue by heisice** [cbestall/node-site-meta#1]
apply please.

[index.js.zip](https://github.com/cbestall/node-site-meta/files/587634/index.js.zip)

**Comment by cbestall** [comment]
Thanks.  I have applied your changes.  I would like to include a test for it.  Any ideas?

**Comment by heisice** [comment]
For example, you can test with these sites.

http://www.kbs.co.kr

and the current code is incorrectly applied.

current result:

{ type: 'html',
  url: 'http://www.kbs.co.kr/',
  meta:
   { title: 'KBS',
     description: 'KBS Ȩ������',
     canonical: '',
     favicon: 'http://www.kbs.co.kr/favicon.ico',
     apple_touch_icon: [],
     feeds: [],
     og:
      { title: 'KBS Ȩ������',
        type: '',
        image: 'http://img.kbs.co.kr/cms/image/kbs_facebook.jpg',
        url: '',
        description: 'KBS Ȩ������',
        site_name: 'KBS' },
     twitter:
      { card: '',
        site: '',
        title: '',
        url: '',
        description: '',
        creator: '',
        image: '' } } }

when request encoding is must null.
then body is raw buffer.

correct result is:

{ type: 'html',
  url: 'http://www.kbs.co.kr/',
  meta:
   { title: 'KBS',
     description: 'KBS 홈페이지',
     canonical: '',
     favicon: 'http://www.kbs.co.kr/favicon.ico',
     apple_touch_icon: [],
     feeds: [],
     og:
      { title: 'KBS 홈페이지',
        type: '',
        image: 'http://img.kbs.co.kr/cms/image/kbs_facebook.jpg',
        url: '',
        description: 'KBS 홈페이지',
        site_name: 'KBS' },
     twitter:
      { card: '',
        site: '',
        title: '',
        url: '',
        description: '',
        creator: '',
        image: '' } } }

please check again.

**Comment by cbestall** [comment]
Thanks, got the change to work.
